[package]
name = "gflow"
version = "0.1.5"
edition = "2021"
authors = ["PuQing <me@puqing.work>"]
license = "MIT"
description = "A lightweight, single-node job scheduler written in Rust."
keywords = ["slurm", "scheduler", "job", "rust"]
readme = "README.md"

[lib]
path = "src/lib.rs"

[[bin]]
name = "gflowd"
path = "src/bin/gflowd/main.rs"

[[bin]]
name = "gflow"
path = "src/main.rs"

[dependencies]
tmux_interface = { version = "0.3.2" }
tokio = { version = "1.43.0", default-features = false, features = [
    "rt-multi-thread",
] }
clap = { version = "4.5.28", features = [
    "cargo",
    "derive",
], default-features = false }
clap-verbosity-flag = { version = "3.0.2", features = [
    "log",
], default-features = false }
clap_complete = "4.5.44"
env_logger = "0.11.6"
log = "0.4.25"
reqwest = { version = "0.12.12", features = ["json"], default-features = false }
axum = { version = "0.8.1", features = [
    "http1",
    "json",
    "macros",
    "tokio",
], default-features = false }
config = { version = "0.15.7", features = ["toml"], default-features = false }
dirs = "6.0.0"
rand = "0.9.0"
serde = { version = "1.0.217", default-features = false, features = [
    "derive",
    "serde_derive",
] }
shellexpand = { version = "3.1.0", features = [
    "tilde",
    "base-0",
], default-features = false }

[build-dependencies]
anyhow = "1.0.95"
vergen-gix = { version = "1.0.6", features = ["build", "cargo"] }

[dev-dependencies]
mockall = "0.13.1"
tempfile = "3.16.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
