[package]
name = "slurmone"
version = "0.1.2"
edition = "2021"
authors = ["PuQing <me@puqing.work>"]
license = "MIT"
description = "A lightweight, single-node job scheduler written in Rust."
keywords = ["slurm", "scheduler", "job", "rust"]
default-run = "slurmone"

[lib]
name = "slurmone"
path = "slurmone/lib.rs"

[[bin]]
name = "slurmone"
path = "slurmone/main.rs"

[[bin]]
name = "slurmoned"
path = "slurmone/bin/slurmoned.rs"

[dependencies]
clap = { version = "4.5.23", features = ["cargo", "derive"] }
daemonize = "0.5.0"
dirs = "5.0.1"
log = "0.4.22"
num_cpus = "1.16.0"
nvml-wrapper = "0.10.0"
rand = "0.8.5"
rmp-serde = "1.3.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
shellexpand = "3.1.0"
tokio = { version = "1.42.0", features = ["full"] }
toml = "0.8.19"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[build-dependencies]
anyhow = "1.0.86"
vergen-gix = { version = "1.0.0", features = ["build", "cargo"] }

[profile.release]
codegen-units = 1
strip = true
lto = true
opt-level = "z"
