[package]
name = "slurmone"
version = "0.1.2"
edition = "2021"
authors = ["PuQing <me@puqing.work>"]
license = "MIT"
description = "A lightweight, single-node job scheduler written in Rust."
keywords = ["slurm", "scheduler", "job", "rust"]

[[bin]]
name = "slurmone/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["cargo", "derive"] }

[build-dependencies]
anyhow = "1.0.86"
vergen-gix = { version = "1.0.0", features = ["build", "cargo"] }

[profile.release]
codegen-units = 1
strip = true
lto = true
opt-level = "z"
